;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


song1_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cd,$cb,$c9,$c8,$c6,$c5,$c4,$c4,$c3,$c2,$c0,$00,$0a
@env2:
	.byte $ce,$cd,$cd,$cc,$cb,$cb,$ca,$02,$c9,$03,$c8,$c8,$c7,$03,$c6,$02
	.byte $c5,$c5,$c4,$02,$c3,$c3,$c2,$03,$c1,$00,$18


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $7a,$80,$1c,$81,$1c,$81,$20,$81,$1c,$81,$1c,$81,$21,$81,$1c,$81
@ref1:
	.byte $1c,$81,$20,$81,$21,$81,$20,$81,$1e,$81,$1c,$81,$1e,$81
@ref2:
	.byte $1c,$81,$1c,$81,$20,$81,$1c,$81,$1c,$81,$21,$81,$1c,$81
	.byte $ff,$0e
	.word @ref1
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $79,$81,$82,$1c,$81,$1c,$81,$20,$81,$1c,$81,$1c,$81,$21,$81,$1c
@ref5:
	.byte $81,$1c,$81,$20,$81,$21,$81,$20,$81,$1e,$81,$1c,$81,$1e
@ref6:
	.byte $81,$1c,$81,$1c,$81,$20,$81,$1c,$81,$1c,$81,$21,$81,$1c
	.byte $ff,$0e
	.word @ref5
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $9b
@ref9:
	.byte $9b
@ref10:
	.byte $9b
@ref11:
	.byte $9b
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $9b
@ref13:
	.byte $9b
@ref14:
	.byte $9b
@ref15:
	.byte $9b
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9b
@ref17:
	.byte $9b
@ref18:
	.byte $9b
@ref19:
	.byte $9b
	.byte $fd
	.word @song0ch4loop
